FROM node:22-alpine AS build

WORKDIR /app/frontend

ARG FRONTEND_API_BASE_URL
ARG FRONTEND_DEV_SERVER_PORT
ARG FRONTEND_DEV_PROXY_TARGET

ENV FRONTEND_API_BASE_URL=${FRONTEND_API_BASE_URL}
ENV FRONTEND_DEV_SERVER_PORT=${FRONTEND_DEV_SERVER_PORT}
ENV FRONTEND_DEV_PROXY_TARGET=${FRONTEND_DEV_PROXY_TARGET}

COPY config /app/config
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

RUN npm run build


FROM nginx:stable-alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]