# שלב 1: בנייה
FROM node:22-alpine AS build
WORKDIR /app

# COPY config /config

# העתקת קבצי ה-npm מתוך תיקיית frontend
COPY frontend/package*.json ./
RUN npm install

# העתקת שאר קוד הפרונטאנד
COPY frontend/ .

# הרצת ה-Build - עכשיו הוא ימצא את ה-YAML
RUN npm run build

# שלב 2: הגשה (Nginx)
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# וודא שקובץ ה-nginx.conf נמצא בתוך תיקיית frontend
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]