FROM node:22-alpine AS build

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/tsconfig.json ./
COPY backend/src ./src
COPY backend/prisma ./prisma

RUN npx prisma generate
RUN npm run build


FROM node:22-alpine AS runtime

WORKDIR /app

COPY backend/package*.json ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/node_modules/@prisma ./node_modules/@prisma

EXPOSE 8000

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && node -r dotenv/config dist/index.js"]